import type { Metadata } from "next";
import "../styles/globals.css";
import Navbar from "@/components/Comman/Navbar";
import Footer from "@/components/Comman/Footer";


export const metadata: Metadata = {
  title: "AL-Ghwasa",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
